//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adaptive.CodeDom.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adaptive.CodeDom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abstract Methods / Functions.
        /// </summary>
        internal static string RegionAbtractMethods {
            get {
                return ResourceManager.GetString("RegionAbtractMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constructor / Dispose Methods.
        /// </summary>
        internal static string RegionConstructorDispose {
            get {
                return ResourceManager.GetString("RegionConstructorDispose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Event Handlers.
        /// </summary>
        internal static string RegionEventHandlers {
            get {
                return ResourceManager.GetString("RegionEventHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Event Methods.
        /// </summary>
        internal static string RegionEventMethods {
            get {
                return ResourceManager.GetString("RegionEventMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Constants.
        /// </summary>
        internal static string RegionPrivateConstants {
            get {
                return ResourceManager.GetString("RegionPrivateConstants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Member Declarations.
        /// </summary>
        internal static string RegionPrivateMembers {
            get {
                return ResourceManager.GetString("RegionPrivateMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private Methods / Functions.
        /// </summary>
        internal static string RegionPrivateMethods {
            get {
                return ResourceManager.GetString("RegionPrivateMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected Methods / Functions.
        /// </summary>
        internal static string RegionProtectedMethods {
            get {
                return ResourceManager.GetString("RegionProtectedMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protected Properties.
        /// </summary>
        internal static string RegionProtectedProperties {
            get {
                return ResourceManager.GetString("RegionProtectedProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Events.
        /// </summary>
        internal static string RegionPublicEvents {
            get {
                return ResourceManager.GetString("RegionPublicEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Methods / Functions.
        /// </summary>
        internal static string RegionPublicMethods {
            get {
                return ResourceManager.GetString("RegionPublicMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public Properties.
        /// </summary>
        internal static string RegionPublicProperties {
            get {
                return ResourceManager.GetString("RegionPublicProperties", resourceCulture);
            }
        }
    }
}
