//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adaptive.Intelligence.SqlServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adaptive.Intelligence.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes the class with an externally provided SQL provider instance for data access operations..
        /// </summary>
        internal static string DaClassConstructorXmlRemarksTemplate {
            get {
                return ResourceManager.GetString("DaClassConstructorXmlRemarksTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the &lt;see cref=\&quot;{0}\&quot;/&gt; class..
        /// </summary>
        internal static string DaClassConstructorXmlSummaryTemplate {
            get {
                return ResourceManager.GetString("DaClassConstructorXmlSummaryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the default constructor..
        /// </summary>
        internal static string DaClassParamLessConstructorXmlRemarksTemplate {
            get {
                return ResourceManager.GetString("DaClassParamLessConstructorXmlRemarksTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializes a new instance of the &lt;see cref=\&quot;{0}\&quot;/&gt; class..
        /// </summary>
        internal static string DaClassParamLessConstructorXmlSummaryTemplate {
            get {
                return ResourceManager.GetString("DaClassParamLessConstructorXmlSummaryTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to provider.
        /// </summary>
        internal static string DaClassProviderVariableName {
            get {
                return ResourceManager.GetString("DaClassProviderVariableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reference to the &lt;see cref=\&quot;{0}&quot;/&gt; instance to use instead of locally creating one..
        /// </summary>
        internal static string DaClassProviderVariableParamSummary {
            get {
                return ResourceManager.GetString("DaClassProviderVariableParamSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlProvider.
        /// </summary>
        internal static string DaClassProviderVariableTypeName {
            get {
                return ResourceManager.GetString("DaClassProviderVariableTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored procedure to delete a record..
        /// </summary>
        internal static string DataAccessSpDeleteXmlSummary {
            get {
                return ResourceManager.GetString("DataAccessSpDeleteXmlSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored procedure to retrieve all the records in the table..
        /// </summary>
        internal static string DataAccessSpGetAllXmlSummary {
            get {
                return ResourceManager.GetString("DataAccessSpGetAllXmlSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored procedure to retrieve a single record by ID value..
        /// </summary>
        internal static string DataAccessSpGetByIdXmlSummary {
            get {
                return ResourceManager.GetString("DataAccessSpGetByIdXmlSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored procedure to insert a record..
        /// </summary>
        internal static string DataAccessSpInsertXmlSummary {
            get {
                return ResourceManager.GetString("DataAccessSpInsertXmlSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The @{0} parameter for a stored procedure..
        /// </summary>
        internal static string DataAccessSpSummaryPrefixForParameter {
            get {
                return ResourceManager.GetString("DataAccessSpSummaryPrefixForParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stored procedure to update a record..
        /// </summary>
        internal static string DataAccessSpUpdateXmlSummary {
            get {
                return ResourceManager.GetString("DataAccessSpUpdateXmlSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DataAccessXmlRemarks {
            get {
                return ResourceManager.GetString("DataAccessXmlRemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides the data access methods for the records in the table..
        /// </summary>
        internal static string DataAccessXmlSummary {
            get {
                return ResourceManager.GetString("DataAccessXmlSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy hh:mm:ss tt.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataAccessBase.
        /// </summary>
        internal static string DefaultDataAccessBaseClassName {
            get {
                return ResourceManager.GetString("DefaultDataAccessBaseClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlDelete.
        /// </summary>
        internal static string DefaultSpConstNameDelete {
            get {
                return ResourceManager.GetString("DefaultSpConstNameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlGetAll.
        /// </summary>
        internal static string DefaultSpConstNameGetAll {
            get {
                return ResourceManager.GetString("DefaultSpConstNameGetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlGetById.
        /// </summary>
        internal static string DefaultSpConstNameGetById {
            get {
                return ResourceManager.GetString("DefaultSpConstNameGetById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlInsert.
        /// </summary>
        internal static string DefaultSpConstNameInsert {
            get {
                return ResourceManager.GetString("DefaultSpConstNameInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlParam.
        /// </summary>
        internal static string DefaultSpConstNameSqlParamPrefix {
            get {
                return ResourceManager.GetString("DefaultSpConstNameSqlParamPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SqlUpdate.
        /// </summary>
        internal static string DefaultSpConstNameUpdate {
            get {
                return ResourceManager.GetString("DefaultSpConstNameUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Fragmentation Statistics.
        /// </summary>
        internal static string StatusCollecting {
            get {
                return ResourceManager.GetString("StatusCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        internal static string StatusConnected {
            get {
                return ResourceManager.GetString("StatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string StatusInitializing {
            get {
                return ResourceManager.GetString("StatusInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing Smart Index Rebuild.
        /// </summary>
        internal static string StatusPerformSmartRebuild {
            get {
                return ResourceManager.GetString("StatusPerformSmartRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting For Recompile....
        /// </summary>
        internal static string StatusSetForRecompile {
            get {
                return ResourceManager.GetString("StatusSetForRecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Statistics On Tables.
        /// </summary>
        internal static string StatusUpdatingStats {
            get {
                return ResourceManager.GetString("StatusUpdatingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Rebuild Execution....
        /// </summary>
        internal static string SubStatusBeginRebuildExec {
            get {
                return ResourceManager.GetString("SubStatusBeginRebuildExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating SQL Statements....
        /// </summary>
        internal static string SubStatusCreatingStatements {
            get {
                return ResourceManager.GetString("SubStatusCreatingStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Smart Rebuild: Pass:.
        /// </summary>
        internal static string SubStatusPass {
            get {
                return ResourceManager.GetString("SubStatusPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Schema Content.....
        /// </summary>
        internal static string SubStatusReadingSchema {
            get {
                return ResourceManager.GetString("SubStatusReadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Operations.
        /// </summary>
        internal static string SubStatusStartOps {
            get {
                return ResourceManager.GetString("SubStatusStartOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Connection....
        /// </summary>
        internal static string SubStatusTestingConnection {
            get {
                return ResourceManager.GetString("SubStatusTestingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	DB_ID()          [DatabaseId], 
        ///	DB_NAME(DB_ID()) [DatabaseName]
        ///
        ///SELECT 
        ///	SCHEMA_NAME([tables].[schema_id]),
        ///	[tables].[name],
        ///	[tables].[object_id] 
        ///FROM
        ///	[sys].[tables] 
        ///WHERE 
        ///   [tables].[type] = &apos;U&apos; OR
        ///   [tables].[type] = &apos;IT&apos;
        ///
        ///ORDER BY 
        ///    [tables].[name] 
        /// 
        ///SELECT 
        ///   [indexes].[object_id], 
        ///   [indexes].[index_id], 
        ///   [indexes].[type], 
        ///   [indexes].[name], 
        ///   [indexes].[is_primary_key] 
        ///FROM 
        ///   [sys].[indexes] 
        ///       INNER JOIN[sys].[tables] 
        ///           ON  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TSqlBasicSchemaQuery {
            get {
                return ResourceManager.GetString("TSqlBasicSchemaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	[sys].[databases].[name]
        ///
        ///FROM 
        ///	[sys].[databases]
        ///
        ///ORDER BY [sys].[databases].[name].
        /// </summary>
        internal static string TSqlGetAllDbNamesQuery {
            get {
                return ResourceManager.GetString("TSqlGetAllDbNamesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	[Types].[name]              typeName,
        ///	[Types].[system_type_id]    typeId,
        ///	[Types].[max_length]        [maxLength],
        ///	[Types].[precision]         [precision],
        ///	[Types].[scale]             [scale],
        ///	[Types].[is_nullable]       isNullable 
        ///FROM
        ///	[sys].[types] [Types] 
        ///WHERE 
        ///   [Types].[is_user_defined] = 0 
        ///ORDER BY 
        ///    [Types].[system_type_id].
        /// </summary>
        internal static string TSqlGetDataTypesQuery {
            get {
                return ResourceManager.GetString("TSqlGetDataTypesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	[sys].[databases].[name]
        ///
        ///FROM 
        ///	[sys].[databases]
        ///
        ///WHERE
        ///	[sys].[databases].[owner_sid] != 1
        ///	AND LEN([sys].[databases].[owner_sid]) &gt; 1
        ///
        ///ORDER BY [name].
        /// </summary>
        internal static string TSqlGetDbNamesQuery {
            get {
                return ResourceManager.GetString("TSqlGetDbNamesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  
        ///	[TableColumns].[object_id]			TableObjectId, 
        ///	SCHEMA_NAME([Tables].[schema_id])	SchemaName,
        ///	[Tables].[name]						TableName,  
        ///	[TableColumns].[column_id]			ColumnId,
        ///	[TableColumns].[name]				ColumnName,
        ///	[TableColumns].[user_type_id]		TypeId, 
        ///	[TableColumns].[max_length]			[MaxLength], 
        ///	[TableColumns].[precision]			[Precision], 
        ///	[TableColumns].[scale]				[Scale],
        ///	[TableColumns].[is_nullable]		IsNullable, 
        ///	[TableColumns].[is_identity]		IsIdentity, 
        ///	[TableColumns].[is_computed]		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TSqlGetTableColumnsQuery {
            get {
                return ResourceManager.GetString("TSqlGetTableColumnsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///   [database_id]		[DatabaseId], 
        ///   [object_id]			[ObjectId], 
        ///   [index_id]			[IndexId], 
        ///   [avg_fragmentation_in_percent]	[AvgFragmentationInPercent], 
        ///   [fragment_count]		[FragmentCount], 
        ///   [page_count]			[PageCount] 
        ///FROM
        ///   sys.dm_db_index_physical_stats(DB_ID(), @ObjectId, NULL, NULL, &apos;DETAILED&apos;) 
        ///ORDER BY
        ///	[database_id],
        ///    [object_id],
        ///	[index_id].
        /// </summary>
        internal static string TSqlIndexFragmentationQuery {
            get {
                return ResourceManager.GetString("TSqlIndexFragmentationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_recompile {0}.
        /// </summary>
        internal static string TSqlRecompileQuery {
            get {
                return ResourceManager.GetString("TSqlRecompileQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE STATISTICS {0}.
        /// </summary>
        internal static string TSqlUpdateStatisticsQuery {
            get {
                return ResourceManager.GetString("TSqlUpdateStatisticsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.
        /// </summary>
        internal static string UsingSystemCollectionsGeneric {
            get {
                return ResourceManager.GetString("UsingSystemCollectionsGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Data.SqlClient.
        /// </summary>
        internal static string UsingSystemDataClient {
            get {
                return ResourceManager.GetString("UsingSystemDataClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Threading.Tasks.
        /// </summary>
        internal static string UsingSystemThreadingTasks {
            get {
                return ResourceManager.GetString("UsingSystemThreadingTasks", resourceCulture);
            }
        }
    }
}
