//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adaptive.Intelligence.SqlServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adaptive.Intelligence.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Fragmentation Statistics.
        /// </summary>
        internal static string StatusCollecting {
            get {
                return ResourceManager.GetString("StatusCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        internal static string StatusConnected {
            get {
                return ResourceManager.GetString("StatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string StatusInitializing {
            get {
                return ResourceManager.GetString("StatusInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing Smart Index Rebuild.
        /// </summary>
        internal static string StatusPerformSmartRebuild {
            get {
                return ResourceManager.GetString("StatusPerformSmartRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting For Recompile....
        /// </summary>
        internal static string StatusSetForRecompile {
            get {
                return ResourceManager.GetString("StatusSetForRecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Statistics On Tables.
        /// </summary>
        internal static string StatusUpdatingStats {
            get {
                return ResourceManager.GetString("StatusUpdatingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Rebuild Execution....
        /// </summary>
        internal static string SubStatusBeginRebuildExec {
            get {
                return ResourceManager.GetString("SubStatusBeginRebuildExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating SQL Statements....
        /// </summary>
        internal static string SubStatusCreatingStatements {
            get {
                return ResourceManager.GetString("SubStatusCreatingStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Smart Rebuild: Pass:.
        /// </summary>
        internal static string SubStatusPass {
            get {
                return ResourceManager.GetString("SubStatusPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Schema Content.....
        /// </summary>
        internal static string SubStatusReadingSchema {
            get {
                return ResourceManager.GetString("SubStatusReadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Operations.
        /// </summary>
        internal static string SubStatusStartOps {
            get {
                return ResourceManager.GetString("SubStatusStartOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Connection....
        /// </summary>
        internal static string SubStatusTestingConnection {
            get {
                return ResourceManager.GetString("SubStatusTestingConnection", resourceCulture);
            }
        }
    }
}
