//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adaptive.Intelligence.SqlServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adaptive.Intelligence.SqlServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MM/dd/yyyy hh:mm:ss tt.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting Fragmentation Statistics.
        /// </summary>
        internal static string StatusCollecting {
            get {
                return ResourceManager.GetString("StatusCollecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected..
        /// </summary>
        internal static string StatusConnected {
            get {
                return ResourceManager.GetString("StatusConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string StatusInitializing {
            get {
                return ResourceManager.GetString("StatusInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing Smart Index Rebuild.
        /// </summary>
        internal static string StatusPerformSmartRebuild {
            get {
                return ResourceManager.GetString("StatusPerformSmartRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting For Recompile....
        /// </summary>
        internal static string StatusSetForRecompile {
            get {
                return ResourceManager.GetString("StatusSetForRecompile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating Statistics On Tables.
        /// </summary>
        internal static string StatusUpdatingStats {
            get {
                return ResourceManager.GetString("StatusUpdatingStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beginning Rebuild Execution....
        /// </summary>
        internal static string SubStatusBeginRebuildExec {
            get {
                return ResourceManager.GetString("SubStatusBeginRebuildExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating SQL Statements....
        /// </summary>
        internal static string SubStatusCreatingStatements {
            get {
                return ResourceManager.GetString("SubStatusCreatingStatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Smart Rebuild: Pass:.
        /// </summary>
        internal static string SubStatusPass {
            get {
                return ResourceManager.GetString("SubStatusPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reading Schema Content.....
        /// </summary>
        internal static string SubStatusReadingSchema {
            get {
                return ResourceManager.GetString("SubStatusReadingSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Operations.
        /// </summary>
        internal static string SubStatusStartOps {
            get {
                return ResourceManager.GetString("SubStatusStartOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing Connection....
        /// </summary>
        internal static string SubStatusTestingConnection {
            get {
                return ResourceManager.GetString("SubStatusTestingConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	DB_ID()          [DatabaseId], 
        ///	DB_NAME(DB_ID()) [DatabaseName]
        ///
        ///SELECT 
        ///	SCHEMA_NAME([tables].[schema_id]),
        ///	[tables].[name],
        ///	[tables].[object_id] 
        ///FROM
        ///	[sys].[tables] 
        ///WHERE 
        ///   [tables].[type] = &apos;U&apos; OR
        ///   [tables].[type] = &apos;IT&apos;
        ///
        ///ORDER BY 
        ///    [tables].[name] 
        /// 
        ///SELECT 
        ///   [indexes].[object_id], 
        ///   [indexes].[index_id], 
        ///   [indexes].[type], 
        ///   [indexes].[name], 
        ///   [indexes].[is_primary_key] 
        ///FROM 
        ///   [sys].[indexes] 
        ///       INNER JOIN[sys].[tables] 
        ///           ON  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TSqlBasicSchemaQuery {
            get {
                return ResourceManager.GetString("TSqlBasicSchemaQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	[sys].[databases].[name]
        ///
        ///FROM 
        ///	[sys].[databases]
        ///
        ///ORDER BY [sys].[databases].[name].
        /// </summary>
        internal static string TSqlGetAllDbNamesQuery {
            get {
                return ResourceManager.GetString("TSqlGetAllDbNamesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///	[sys].[databases].[name]
        ///
        ///FROM 
        ///	[sys].[databases]
        ///
        ///WHERE
        ///	[sys].[databases].[owner_sid] != 1
        ///	AND LEN([sys].[databases].[owner_sid]) &gt; 1
        ///
        ///ORDER BY [name].
        /// </summary>
        internal static string TSqlGetDbNamesQuery {
            get {
                return ResourceManager.GetString("TSqlGetDbNamesQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT  
        ///	[TableColumns].[object_id]			TableObjectId, 
        ///	SCHEMA_NAME([Tables].[schema_id])	SchemaName,
        ///	[Tables].[name]						TableName,  
        ///	[TableColumns].[column_id]			ColumnId,
        ///	[TableColumns].[name]				ColumnName,
        ///	[TableColumns].[user_type_id]		TypeId, 
        ///	[TableColumns].[max_length]			[MaxLength], 
        ///	[TableColumns].[precision]			[Precision], 
        ///	[TableColumns].[scale]				[Scale],
        ///	[TableColumns].[is_nullable]		IsNullable, 
        ///	[TableColumns].[is_identity]		IsIdentity, 
        ///	[TableColumns].[is_computed]		 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TSqlGetTableColumnsQuery {
            get {
                return ResourceManager.GetString("TSqlGetTableColumnsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT 
        ///   [database_id]		[DatabaseId], 
        ///   [object_id]			[ObjectId], 
        ///   [index_id]			[IndexId], 
        ///   [avg_fragmentation_in_percent]	[AvgFragmentationInPercent], 
        ///   [fragment_count]		[FragmentCount], 
        ///   [page_count]			[PageCount] 
        ///FROM
        ///   sys.dm_db_index_physical_stats(DB_ID(), @ObjectId, NULL, NULL, &apos;DETAILED&apos;) 
        ///ORDER BY
        ///	[database_id],
        ///    [object_id],
        ///	[index_id].
        /// </summary>
        internal static string TSqlIndexFragmentationQuery {
            get {
                return ResourceManager.GetString("TSqlIndexFragmentationQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exec sp_recompile {0}.
        /// </summary>
        internal static string TSqlRecompileQuery {
            get {
                return ResourceManager.GetString("TSqlRecompileQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE STATISTICS {0}.
        /// </summary>
        internal static string TSqlUpdateStatisticsQuery {
            get {
                return ResourceManager.GetString("TSqlUpdateStatisticsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Collections.Generic.
        /// </summary>
        internal static string UsingSystemCollectionsGeneric {
            get {
                return ResourceManager.GetString("UsingSystemCollectionsGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Data.SqlClient.
        /// </summary>
        internal static string UsingSystemDataClient {
            get {
                return ResourceManager.GetString("UsingSystemDataClient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.Threading.Tasks.
        /// </summary>
        internal static string UsingSystemThreadingTasks {
            get {
                return ResourceManager.GetString("UsingSystemThreadingTasks", resourceCulture);
            }
        }
    }
}
