name: Adaptive Intelligence Framework Automated Testing
on: [push]
jobs:
  windows_test:
    runs-on: windows-latest
    steps:
    - name: Check out Code
      uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    - name: Restore Packages
      run: dotnet restore
    - name: Build
      run: dotnet build 
    - name: Run tests
      run: dotnet test
      
